// header 网页头部 action类型
export const GET_SEARCH_SUGGEST = "GET_DROPDOWN_DATA"
export const SEARCH_IPT = "SEARCH_IPT"
export const SEARCH_FOCUS_CHANGE = "SEARCH_FOCUS_CHANGE"

// discover recommend

export const GET_BANNER_OVER = "GET_BANNER_OVER"
// export const CHANGE_BANNER = "CHANGE_BANNER"

export const GET_HOTRECOMMEND_OVER = "GET_HOTRECOMMEND_OVER"

export const GET_RECOMMEND_NEW_OVER = "GET_RECOMMEND_NEW_OVER"

export const GET_RISING_TOPLIST_OVER = "GET_RISING_TOPLIST_OVER"

export const GET_NEW_TOPLIST_OVER = "GET_NEW_TOPLIST_OVER"

export const GET_ORIGINAL_TOPLIST_OVER = "GET_ORIGINAL_TOPLIST_OVER"

export const GET_RECOMMEND_SINGER_OVER = "GET_RECOMMEND_SINGER_OVER"

export const GET_RECOMMEND_ANCHOR_OVER = "GET_RECOMMEND_ANCHOR_OVER"
// 
export const GET_TOPLIST_OVER = "GET_TOPLIST_OVER"

// 
// export const GET_DEFAULT_PLAY_OVER = "GET_DEFAULT_PLAY_OVER"
export const SET_PLAY_SONG = "SET_PLAY_SONG"
export const SET_PLAYLIST = "SET_PLAYLIST"
export const SET_PLAY_IDX = "SET_PLAY_IDX"
